name: Delete DynamoDB Item

on:
  workflow_dispatch:
    inputs:
      delete-key:
        description: "TF Hash to be deleted from DynamoDB (complete string)"
        required: true

env:
  AWS_REGION: ap-northeast-1
  TABLE: testing-tfstate

jobs:
  delete-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete Hash
        run: |
          aws dynamodb delete-item \
            --table-name ${{  env.TABLE }} \
            --key '{"LockID": {"S": "${{ github.event.inputs.delete-key }}"}}'
